DROP TABLE IF EXISTS LocalizedText;
CREATE TABLE LocalizedText (
  Language text,
  Tag text,
  Text text,
  Gender text,
  Plurality text,
  PRIMARY KEY (Language,Tag)
);

CREATE INDEX LocalizedText_ByTag ON LocalizedText (Tag ASC);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CIV5_FEATURES_EL_DORADO_HELP','Der erste Spieler der dies entdeckt, erhält 500 [ICON_GOLD] Gold.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CIV5_FEATURES_EL_DORADO_TEXT','Diese sagenumwobene untergegangene Stadt aus Gold zog viele spanische Konquistadoren wie ein Magnet in die Neue Welt, die alle hofften, auf ihre unvorstellbaren Reichtümer zu stoßen. Fast drei Jahrhunderte lang folgten Entdecker dem Mythos der wertvollen Edelsteine und Goldschätze an die südamerikanischen Küsten und plünderten auf dem Weg oft andere Städte, die sie vorfanden. El Dorado hat im Laufe der Jahrhunderte immer wieder Entdecker fasziniert und noch bis 1804 wurden Expeditionen auf die Suche nach diesem Ort geschickt. Heute geht man allerdings davon aus, dass die mythische Stadt aus dem Namen eines Muisca-Häuptlings entstanden ist, der sich, so wird berichtet, bei einem Initiationsritus selbst mit einer feinen Schicht aus Goldstaub bedeckte und in den Guatavita-See sprang.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CIV5_FEATURES_FOUNTAIN_YOUTH_HELP','Benachbarte Einheiten heilen für den Rest des Spiels doppelt so schnell.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CIV5_FEATURES_FOUNTAIN_YOUTH_TEXT','Eines der ersten Zeugnisse über diesen legendären Brunnen stammt von Herodot, der ihn als eine Art "Wasser des Lebens" beschreibt, das jedem, der es trinkt, ein außergewöhnlich langes Leben schenkt. Ähnliche Geschichten gibt es auch bei den Urvölkern in der Karibik und in Südamerika, durch die der Jungbrunnen im Zuge der spanischen Entdeckungsreisen Berühmtheit erlangte. Einer weit verbreiteten Geschichte zufolge soll der spanische Konquistador Juan Ponce de León 1513 während seiner Reisen in Puerto Rico Erzählungen über den Brunnen gehört und anschließend die Segel gesetzt haben, um das ewige Leben zu finden. So entdeckte er zwar Florida (und war somit einer der ersten Europäer, die nordamerikanischen Boden betraten), aber den mythischen Brunnen fand er nicht. Der Jungbrunnen fasziniert die Menschen bis heute - Filme, Bücher, Comics und Spiele handeln von dem sagenumwobenen Brunnen und der unaufhörlichen Suche der Menschheit nach ihm.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CIV5_FEATURES_POTOSI_TEXT','Der Berg Potosí im Süden Boliviens hat fast das gesamte Silber hervorgebracht, das die Spanier in der Blütezeit ihres Imperiums abbauten. Nach dem Abbau wurde es mit Lamas und Maultieren an die Küste gebracht und dort auf Schiffe verladen, die zurück nach Europa segelten. Fast 41.000 Tonnen pures Silber wurden in 200 Jahren abgebaut, von denen 8.200 Tonnen direkt an die spanische Krone gingen. Nach 1800 waren die Vorkommen in den größten Silberminen erschöpft, doch bis heute gibt es am Potosí aktive Minen. In manchen wird Silber abgebaut, in den meisten jedoch Zinn.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CIV5_FEATURES_FOUNTAIN_YOUTH_TEXT','One of the earliest accounts of this legendary spring comes from Herodotus, who describes it as a special "Water of Life" giving any who drinks of it exceptionally long life.  Similar stories have also been told among the indigenous people of the Caribbean and South America, which brought the Fountain of Youth to prominence during Spain\'s era of exploration.  According to one popular story, in 1513 the Spanish conquistador Juan Ponce de Leon heard tales of the fountain during his travels in Puerto Rico, and set sail to search for eternal life.  In doing so, he discovered Florida (and become one of the first Europeans to set foot on American soil) but never did locate the mythical fountain.  The Fountain of Youth continues to captivate audiences today - movies, books, comics, and games have all featured the fabled spring and man\'s eternal quest to obtain it.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CIV5_FEATURES_FOUNTAIN_YOUTH_HELP','All units that are next to it heal at double rate for the rest of the game.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CIV5_FEATURES_POTOSI_TEXT','Located in southern Bolivia, the mountain of Potosi produced nearly all of the silver mined by the Spanish during their imperial days.  Once removed from the mountain, it was taken by llama and mule to the coast where it was then loaded onto treasure ships sailing back to Europe.   Nearly 41,000 tons of pure silver were mined over the course of 200 years, 8,200 of which went directly to the Spanish crown.  After 1800, the main silver mines were depleted, but the mining of Potosi still continues today - some for silver but now mostly for tin.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CIV5_FEATURES_EL_DORADO_TEXT','This fabled "Lost City of Gold" drew many Spanish conquistadors to the New World, all hoping to stumble upon its untold riches. For nearly three centuries, the myth of precious gems and gold drew explorers to the South American coasts, who often sacked other cities they found along the way. El Dorado has captivated explorers throughout the centuries, and expeditions as late as 1804 were arranged to divine its location. However, it is now believed that the mythical city was inspired by the name of a Muisca chief, who reportedly, as part of an initiation, covered himself in a fine layer of gold dust and dove into the Guatavita Lake.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CIV5_FEATURES_EL_DORADO_HELP','Grants 500 [ICON_GOLD] Gold to the first player to discover it.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CIV5_FEATURES_EL_DORADO_HELP','Octroie 500 [ICON_GOLD] d\'Or au premier joueur qui le découvre.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CIV5_FEATURES_EL_DORADO_TEXT','Cette légendaire "cité d\'or" a attiré de nombreux conquistadors espagnols au Nouveau Monde, dans le fol espoir de mettre la main sur ses incroyables richesses. Pendant près de trois siècles, de nombreux explorateurs appâtés par l\'or et les pierres précieuses ont débarqué sur les côtes d\'Amérique du Sud en mettant à sac les différentes villes sur leur passage. L\'Eldorado a continué de fasciner les aventuriers à travers les siècles, et des expéditions furent organisées au moins jusqu\'en 1804 pour tenter de retrouver la trace de la cité perdue. On pense aujourd\'hui que le mythe est inspiré du nom d\'un chef chibcha, qui, d\'après la légende, se serait entièrement recouvert d\'une fine couche de poussière d\'or lors de son intronisation, avant de plonger dans le lac sacré de Guatavita.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CIV5_FEATURES_FOUNTAIN_YOUTH_HELP','Toutes les unités qui l\'ont approché se soigne deux fois plus rapidement pour le reste de la partie',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CIV5_FEATURES_FOUNTAIN_YOUTH_TEXT','L\'une des toutes premières mentions de cette source légendaire reviendrait à Hérodote, qui en parlait comme d\'une "fontaine de vie" dont l\'eau conférait à quiconque la buvait une vie exceptionnellement longue. On recense des contes similaires chez les peuples des Caraïbes et d\'Amérique du Sud, ce qui rendit la fontaine de jouvence particulièrement recherchée au cours des années d\'exploration de l\'Espagne. À en croire une histoire fort populaire, en 1513, le conquistador espagnol Juan Ponce de León entendit parler de cette fontaine au cours de ses voyages à Porto Rico, et décida de partir à la recherche de la vie éternelle. Malheureusement pour lui, il ne découvrit "que" la Floride (et devint au passage l\'un des premiers Européens à fouler le sol américain), mais ne parvint jamais à localiser la source mythique. Aujourd\'hui encore, la fontaine de jouvence continue à fasciner les foules ; elle est largement évoquée aussi bien dans les films que dans les livres ou dans les jeux.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CIV5_FEATURES_POTOSI_TEXT','Située au sud de la Bolivie, la montagne de Potosí était la principale source d\'argent de l\'empire espagnol. Une fois excavé, le précieux métal était transporté à dos de lamas et de mulets jusqu\'à la côte, où il était alors chargé sur des navires pour être acheminé jusqu\'en Europe. Près de 41 000 tonnes d\'argent pur furent ainsi excavées sur deux siècles, parmi lesquelles 8 200 tonnes firent le bonheur direct de la couronne. L\'argent se fit malheureusement rare à partir de 1800, mais les mines de Potosí sont toujours exploitées de nos jours, certaines encore pour l\'argent, la plupart principalement pour l\'étain.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_FEATURE_EL_DORADO','El Dorado',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_FEATURE_FOUNTAIN_YOUTH','Jungbrunnen',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_FEATURE_POTOSI','Cerro de Potosi',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_FEATURE_FOUNTAIN_YOUTH','Fountain of Youth',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_FEATURE_POTOSI','Cerro de Potosi',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_FEATURE_EL_DORADO','El Dorado',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_FEATURE_EL_DORADO','Eldorado','masculine:vowel','1');
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_FEATURE_FOUNTAIN_YOUTH','Fontaine de jouvence','feminine','1');
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_FEATURE_POTOSI','Cerro de Potosí','masculine','1');
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_MAP_FOLDER_DLC_1_DESC','\'Entdecker\'-Map-Pack',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_MAP_FOLDER_DLC_1_TITLE','Entdecker',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_MAP_FOLDER_DLC_1_TITLE','Explorers',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_MAP_FOLDER_DLC_1_DESC','Explorers Map Pack',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_MAP_FOLDER_DLC_1_DESC','Pack de cartes Explorateurs',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_MAP_FOLDER_DLC_1_TITLE','Explorateurs',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_AFRICA','Afrika',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_AFRICA_DESC','Eine Karte von Afrika. Zufällig generiert bis auf einige wichtige Merkmale.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_AFRICA_DUEL','Afrika - Duell',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_AFRICA_LARGE','Afrika - Groß',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_AFRICA_SMALL','Afrika - Klein',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_AFRICA_STANDARD','Afrika - Standard',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_ANTARCTICA_THAWED','Aufgetaute Antarktis',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_ANTARCTICA_THAWED_DESC','Eine zufällig generierte Version der Antarktis, bei der nur ein kleiner Teil gefroren bleibt.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_EARTH','Erde',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_EARTH_DESC','Die gesamte Erde mit geografisch korrekten Landformen. Das Gelände und die Geländearten sind zufällig generiert.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_EARTH_DUEL','Erde - Duell',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_EARTH_HUGE','Erde - Riesig',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_EARTH_LARGE','Erde - Groß',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_EARTH_SMALL','Erde - Klein',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_EARTH_STANDARD','Erde - Standard',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_EARTH_TINY','Erde - Winzig',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_EAST_ASIA','Ostasien',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_EAST_ASIA_DESC','Eine Karte von Ostasien, bei der die Landformen und der Himalaya gleich bleiben, das übrige Gelände aber zufällig generiert wird.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_EAST_ASIA_LARGE','Ostasien - Groß',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_EAST_ASIA_LARGE_DESC','Eine große Karte von Ostasien, bei der die Landformen und der Himalaya gleich bleiben, das übrige Gelände aber zufällig generiert wird.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_EAST_ASIA_SMALL','Ostasien - Klein',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_EAST_ASIA_SMALL_DESC','Eine kleine Karte von Ostasien, bei der die Landformen und der Himalaya gleich bleiben, das übrige Gelände aber zufällig generiert wird.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_MIDDLE_EAST','Naher Osten',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_MIDDLE_EAST_DESC','Eine Karte des Nahen Ostens vom Schwarzen bis zum Arabischen Meer. Die Landformen bleiben gleich, das übrige Gelände wird zufällig generiert.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_MIDDLE_EAST_DUEL','Naher Osten - Duell',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_MIDDLE_EAST_LARGE','Naher Osten - Groß',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_MIDDLE_EAST_SMALL','Naher Osten - Klein',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_MIDDLE_EAST_STANDARD','Naher Osten - Standard',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_MIDDLE_EAST_TINY','Naher Osten - Winzig',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_NORTH_AMERICA','Nordamerika',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_NORTH_AMERICA_DESC','Eine Karte von Nordamerika von Kolumbien bis Alaska. Landformen und nördliche Tundra bleiben gleich. Gelände und Geländearten werden zufällig generiert.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_NORTH_AMERICA_DUEL','Nordamerika - Duell',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_NORTH_AMERICA_HUGE','Nordamerika - Riesig',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_NORTH_AMERICA_LARGE','Nordamerika - Groß',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_NORTH_AMERICA_SMALL','Nordamerika - Klein',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_NORTH_AMERICA_STANDARD','Nordamerika - Standard',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_NORTH_AMERICA_TINY','Nordamerika - Winzig',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_OCEANIA','Ozeanien',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_OCEANIA_DESC','Ähnelt dem Archipel, wirkt aber kompakter mit zerbrochenen Kontinenten, kleinen Inseln und viel offenem Meer.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_SMALL_CONT_PLUS','Kleine Kontinente Plus',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_SMALL_CONT_PLUS_DESC','Eine neue Interpretation der ursprünglichen \'Kleine Kontinente\'-Karte mit ausgedehnten Inselketten und einer besseren Kontinent-Generierung.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_SOUTH_AMERICA','Südamerika',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_SOUTH_AMERICA_DESC','Eine Karte von Südamerika, bei der die Landform gleich bleibt. Das übrige Gelände und die Geländearten sowie "wandernde" Gebirgszüge werden zufällig erzeugt.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_SOUTH_AMERICA_STANDARD','Südamerika - Standard',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_SOUTH_AMERICA_TINY','Südamerika - Winzig',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_WESTERN_EUROPE','Westeuropa',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_WESTERN_EUROPE_DESC','Eine Karte von Westeuropa, bei der die Landformen und Gebirgszüge gleich bleiben, das übrige Gelände und die Geländearten aber zufällig generiert werden.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_WESTERN_EUROPE_SMALL','Westeuropa - Klein',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_WESTERN_EUROPE_SMALL_DESC','Eine kleine Karte von Westeuropa, bei der die Landformen und Gebirgszüge gleich bleiben, das übrige Gelände und die Geländearten aber zufällig generiert werden.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_WESTERN_EUROPE_STANDARD','Westeuropa - Standard',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_WESTERN_EUROPE_STANDARD_DESC','Eine Standardkarte von Westeuropa, bei der die Landformen und Gebirgszüge gleich bleiben, das übrige Gelände und die Geländearten aber zufällig generiert werden.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_MAP_FOLDER_DLC_2_DESC','\'Verwandelte Kontinente\'-Map-Pack',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_MAP_FOLDER_DLC_2_TITLE','Verwandelte Kontinente',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_MAP_FOLDER_DLC_2_TITLE','Scrambled Continents',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_MAP_FOLDER_DLC_2_DESC','Scrambled Continents Map Pack',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_AFRICA','Africa',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_AFRICA_DUEL','Africa - Duel',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_AFRICA_SMALL','Africa - Small',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_AFRICA_STANDARD','Africa - Standard',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_AFRICA_LARGE','Africa - Large',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_AFRICA_DESC','A map of Africa, randomized except for some key features.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_ANTARCTICA_THAWED','Antarctica Thawed',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_ANTARCTICA_THAWED_DESC','A randomized fantasy version of Antarctica where only a small portion remains frozen.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_EARTH','Earth',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_EARTH_TINY','Earth - Tiny',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_EARTH_DUEL','Earth - Duel',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_EARTH_SMALL','Earth - Small',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_EARTH_STANDARD','Earth - Standard',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_EARTH_LARGE','Earth - Large',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_EARTH_HUGE','Earth - Huge',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_EARTH_DESC','The entire Earth, with geographically correct landforms and randomized terrain and features.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_EAST_ASIA','East Asia',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_EAST_ASIA_DESC','A map of Eastern Asia, where the landforms and the Himalayas are constant, with all other terrain randomized.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_EAST_ASIA_SMALL','East Asia - Small',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_EAST_ASIA_SMALL_DESC','A small map of Eastern Asia, where the landforms and the Himalayas are constant, with all other terrain randomized.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_EAST_ASIA_LARGE','East Asia - Large',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_EAST_ASIA_LARGE_DESC','A large map of Eastern Asia, where the landforms and the Himalayas are constant, with all other terrain randomized.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_WESTERN_EUROPE','Western Europe',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_WESTERN_EUROPE_DESC','A map of Western Europe, where the landforms and mountain ranges are constant, with all other terrain and features randomized.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_WESTERN_EUROPE_SMALL','Western Europe - Small',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_WESTERN_EUROPE_SMALL_DESC','A small map of Western Europe, where the landforms and mountain ranges are constant, with all other terrain and features randomized.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_WESTERN_EUROPE_STANDARD','Western Europe - Standard',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_WESTERN_EUROPE_STANDARD_DESC','A standard map of Western Europe, where the landforms and mountain ranges are constant, with all other terrain and features randomized.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_OCEANIA','Oceania',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_OCEANIA_DESC','Similar to Archipelago, with more of a continental feel with clusters of broken continents, small islands, and plenty of open water.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_SMALL_CONT_PLUS','Small Continents Plus',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_SMALL_CONT_PLUS_DESC','A new approach to the original Small Continents map, adding sprawling island chains and better continent generation.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_NORTH_AMERICA','North America',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_NORTH_AMERICA_DUEL','North America - Duel',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_NORTH_AMERICA_TINY','North America - Tiny',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_NORTH_AMERICA_SMALL','North America - Small',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_NORTH_AMERICA_STANDARD','North America - Standard',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_NORTH_AMERICA_LARGE','North America - Large',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_NORTH_AMERICA_HUGE','North America - Huge',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_NORTH_AMERICA_DESC','A map of North America spanning Colombia to Alaska, where the landforms and northern tundra are constant, and all other terrain and features are randomized.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_SOUTH_AMERICA','South America',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_SOUTH_AMERICA_TINY','South America - Tiny',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_SOUTH_AMERICA_STANDARD','South America - Standard',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_SOUTH_AMERICA_DESC','A map of South America, where the landform is constant, and all other terrain and features randomized, including the "wandering" mountain ranges.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_MIDDLE_EAST','Middle East',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_MIDDLE_EAST_DUEL','Middle East - Duel',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_MIDDLE_EAST_TINY','Middle East - Tiny',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_MIDDLE_EAST_SMALL','Middle East - Small',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_MIDDLE_EAST_STANDARD','Middle East - Standard',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_MIDDLE_EAST_LARGE','Middle East - Large',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_MIDDLE_EAST_DESC','A map of the Middle East spanning the Black Sea to the Arabian Sea, where the landforms are constant, and all other terrain is randomized.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_AFRICA','Afrique',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_AFRICA_DESC','Une carte de l\'Afrique, générée aléatoirement à l\'exception de quelques caractéristiques clés.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_AFRICA_DUEL','Afrique - Duel',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_AFRICA_LARGE','Afrique - Grande',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_AFRICA_SMALL','Afrique - Petite',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_AFRICA_STANDARD','Afrique - Normale',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_ANTARCTICA_THAWED','Antarctique réchauffé',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_ANTARCTICA_THAWED_DESC','Une version imaginaire de l\'Antarctique, générée aléatoirement, où seule une petite portion du continent reste gelée.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_EARTH','Terre',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_EARTH_DESC','La Terre tout entière, avec la forme correcte des terres émergées, mais où les terrains et caractéristiques sont générés aléatoirement.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_EARTH_DUEL','Terre - Duel',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_EARTH_HUGE','Terre - Immense',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_EARTH_LARGE','Terre - Grande',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_EARTH_SMALL','Terre - Petite',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_EARTH_STANDARD','Terre - Normale',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_EARTH_TINY','Terre - Minuscule',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_EAST_ASIA','Asie de l\'Est',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_EAST_ASIA_DESC','Une carte de l\'Asie de l\'Est, où la forme des terres émergées et la position de l\'Himalaya sont constantes, mais où les autres terrains sont générés aléatoirement.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_EAST_ASIA_LARGE','Asie de l\'Est - Grande',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_EAST_ASIA_LARGE_DESC','Une grande carte de l\'Asie de l\'Est, où la forme des terres émergées et la position de l\'Himalaya sont constantes, mais où les autres terrains sont générés aléatoirement.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_EAST_ASIA_SMALL','Asie de l\'Est - Petite',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_EAST_ASIA_SMALL_DESC','Une petite carte de l\'Asie de l\'Est, où la forme des terres émergées et la position de l\'Himalaya sont constantes, mais où les autres terrains sont générés aléatoirement.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_MIDDLE_EAST','Moyen-Orient',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_MIDDLE_EAST_DESC','Carte qui s\'étend de la mer Noire à la mer d\'Oman, où la forme des terres est constante, mais où le terrain est aléatoire.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_MIDDLE_EAST_DUEL','Moyen-Orient - Duel',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_MIDDLE_EAST_LARGE','Moyen-Orient - Grande',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_MIDDLE_EAST_SMALL','Moyen-Orient - Petite',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_MIDDLE_EAST_STANDARD','Moyen-Orient - Normale',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_MIDDLE_EAST_TINY','Moyen-Orient - Minuscule',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_NORTH_AMERICA','Amérique du Nord',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_NORTH_AMERICA_DESC','Carte de l\'Amérique du Nord, depuis la Colombie jusqu\'à l\'Alaska, où les formes terrestres et la toundra sont constantes, mais où terrain et attributs sont aléatoires.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_NORTH_AMERICA_DUEL','Amérique du Nord - Duel',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_NORTH_AMERICA_HUGE','Amérique du Nord - Immense',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_NORTH_AMERICA_LARGE','Amérique du Nord - Grande',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_NORTH_AMERICA_SMALL','Amérique du Nord - Petite',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_NORTH_AMERICA_STANDARD','Amérique du Nord - Normale',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_NORTH_AMERICA_TINY','Amérique du Nord - Minuscule',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_OCEANIA','Océanie',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_OCEANIA_DESC','Similaire à la carte Archipel, mais les continents brisés, les petites îles et les larges étendues d\'eau donnent une impression plus continentale à cette carte.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_SMALL_CONT_PLUS','Petits continents Plus',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_SMALL_CONT_PLUS_DESC','Une version repensée de la carte Petits continents, où les regroupements d\'îles sont plus nombreux et où les continents sont mieux générés.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_SOUTH_AMERICA','Amérique du Sud',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_SOUTH_AMERICA_DESC','Carte d\'Amérique du Sud où la position des terres est constante, mais où terrains et caractéristiques, y compris les chaînes de montagnes, sont aléatoires.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_SOUTH_AMERICA_STANDARD','Amérique du Sud - Normale',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_SOUTH_AMERICA_TINY','Amérique du Sud - Minuscule',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_WESTERN_EUROPE','Europe occidentale',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_WESTERN_EUROPE_DESC','Carte de l\'Europe occidentale où les positions des terres et des chaînes de montagnes sont constantes, mais où terrains et caractéristiques sont aléatoires.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_WESTERN_EUROPE_SMALL','Europe occidentale - Petite',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_WESTERN_EUROPE_SMALL_DESC','Une petite carte de l\'Europe occidentale, où la forme des terres émergées et la position des chaînes de montagnes sont constantes, mais où les autres terrains et caractéristiques sont générés aléatoirement.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_WESTERN_EUROPE_STANDARD','Europe occidentale - Normale',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_WESTERN_EUROPE_STANDARD_DESC','Une carte normale de l\'Europe occidentale, où la forme des terres émergées et la position des chaînes de montagnes sont constantes, mais où les autres terrains et caractéristiques sont générés aléatoirement.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_MAP_FOLDER_DLC_2_DESC','Pack de cartes Continents dispersés',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_MAP_FOLDER_DLC_2_TITLE','Continents dispersés',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_AUSTRALIA','Australien',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_AUSTRALIA_DESC','Eine Karte von Australien mit zufällig generiertem Gelände und Startpositionen an der Küste.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_AUSTRALIA_DUEL','Australien - Duell',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_AUSTRALIA_SMALL','Australien - Klein',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_AUSTRALIA_STANDARD','Australien - Standard',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_AUSTRALIA_TINY','Australien - Winzig',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_CANADA','Kanada',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_CANADA_DESC','Eine Karte von Kanada mit Tundra und Schnee im Norden und zufällig generierten Ebenen, Grasland und Waldflächen.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_CANADA_DUEL','Kanada - Duell',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_CANADA_LARGE','Kanada - Groß',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_CANADA_SMALL','Kanada - Klein',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_CANADA_STANDARD','Kanada - Standard',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_CANADA_TINY','Kanada - Winzig',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_CHINA','China',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_CHINA_DESC','Eine komplett zufällig generierte Karte, bei der die Landformen und das Gelände China ähnlich sind.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_CHINA_DUEL','China - Duell',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_CHINA_LARGE','China - Groß',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_CHINA_SMALL','China - Klein',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_CHINA_STANDARD','China - Standard',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_CHINA_TINY','China - Winzig',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_FRANCE','Frankreich',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_FRANCE_DESC','Eine Karte von Frankreich, bei der die Landformen gleich bleiben, das Gelände im Inneren aber zufällig generiert wird.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_FRANCE_DUEL','Frankreich - Duell',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_FRANCE_HUGE','Frankreich - Riesig',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_FRANCE_LARGE','Frankreich - Groß',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_FRANCE_SMALL','Frankreich - Klein',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_FRANCE_STANDARD','Frankreich - Standard',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_FRANCE_TINY','Frankreich - Winzig',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_ITALY','Italien',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_ITALY_DESC','Eine Karte von Italien, bei der die Landformen und die Alpen gleich bleiben, das übrige Gelände aber zufällig generiert wird.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_ITALY_SMALL','Italien - Klein',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_ITALY_STANDARD','Italien - Standard',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_JAPAN','Japan',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_JAPAN_DESC','Eine Karte von Japan, bei der die Landformen und wichtigsten Gebirge gleich bleiben, das übrige Gelände aber zufällig generiert wird.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_JAPAN_DUEL','Japan - Duell',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_JAPAN_LARGE','Japan - Groß',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_JAPAN_SMALL','Japan - Klein',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_JAPAN_STANDARD','Japan - Standard',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_JAPAN_TINY','Japan - Winzig',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_RUSSIA','Russland',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_RUSSIA_DESC','Eine Karte von Russland, bei der die Landformen gleich bleiben, das Gelände im Inneren aber zufällig generiert wird.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_RUSSIA_DUEL','Russland - Duell',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_RUSSIA_HUGE','Russland - Riesig',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_RUSSIA_LARGE','Russland - Groß',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_RUSSIA_SMALL','Russland - Klein',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_RUSSIA_STANDARD','Russland - Standard',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_RUSSIA_TINY','Russland - Winzig',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_SCAN','Skandinavien',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_SCAN_DESC','Eine Karte von Skandinavien, die bis auf einige wichtige Merkmale zufällig generiert wird.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_SCAN_LARGE','Skandinavien - Groß',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_SCAN_SMALL','Skandinavien - Klein',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_SCAN_STANDARD','Skandinavien - Standard',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_TURKEY','Türkei',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_TURKEY_DESC','Eine Karte von der Türkei, bei der die Landformen gleich bleiben, das Gelände im Inneren bergig und zufällig generiert wird.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_TURKEY_DUEL','Türkei - Duell',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_TURKEY_HUGE','Türkei - Riesig',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_TURKEY_LARGE','Türkei - Groß',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_TURKEY_SMALL','Türkei - Klein',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_TURKEY_STANDARD','Türkei - Standard',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_TURKEY_TINY','Türkei - Winzig',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_UK','Vereinigtes Königreich',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_UK_DESC','Eine Karte vom Vereinigten Königreich mit England, Schottland und Nordirland, bei der das Gelände zufällig generiert wird.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_UK_DUEL','Vereinigtes Königreich - Duell',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_UK_LARGE','Vereinigtes Königreich - Groß',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_UK_SMALL','Vereinigtes Königreich - Klein',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_UK_STANDARD','Vereinigtes Königreich - Standard',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_CW_MAP_PACK_UK_TINY','Vereinigtes Königreich - Winzig',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_MAP_FOLDER_DLC_3_DESC','\'Verwandelte Nationen\'-Map-Pack',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('de_DE','TXT_KEY_MAP_FOLDER_DLC_3_TITLE','Verwandelte Nationen',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_MAP_FOLDER_DLC_3_TITLE','Scrambled Nations',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_MAP_FOLDER_DLC_3_DESC','Scrambled Nations Map Pack',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_AUSTRALIA','Australia',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_AUSTRALIA_DESC','A map of Australia, with randomized terrain and coastal start locations.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_AUSTRALIA_DUEL','Australia - Duel',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_AUSTRALIA_TINY','Australia - Tiny',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_AUSTRALIA_SMALL','Australia - Small',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_AUSTRALIA_STANDARD','Australia - Standard',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_CANADA','Canada',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_CANADA_DESC','A map of Canada with northern banding of tundra and snow, and randomly generated swaths of plains, grasslands and forest.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_CANADA_DUEL','Canada - Duel',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_CANADA_TINY','Canada - Tiny',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_CANADA_SMALL','Canada - Small',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_CANADA_STANDARD','Canada - Standard',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_CANADA_LARGE','Canada - Large',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_SCAN','Scandinavia',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_SCAN_DESC','A map of Scandinavia, randomized except for some key features.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_SCAN_LARGE','Scandinavia - Large',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_SCAN_STANDARD','Scandinavia - Standard',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_SCAN_SMALL','Scandinavia - Small',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_JAPAN','Japan',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_JAPAN_DESC','A map of Japan, where the landform and key mountains are constant, and all other terrain is randomized.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_JAPAN_DUEL','Japan - Duel',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_JAPAN_TINY','Japan - Tiny',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_JAPAN_SMALL','Japan - Small',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_JAPAN_STANDARD','Japan - Standard',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_JAPAN_LARGE','Japan - Large',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_ITALY','Italy',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_ITALY_DESC','A map of Italy, where the landform and the Alps are constant, with all other terrain randomized.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_ITALY_SMALL','Italy - Small',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_ITALY_STANDARD','Italy - Standard',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_UK','United Kingdom',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_UK_DESC','A map of the United Kingdom, including England, Scotland and Northern Ireland, with all terrain randomized.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_UK_DUEL','United Kingdom - Duel',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_UK_TINY','United Kingdom - Tiny',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_UK_SMALL','United Kingdom - Small',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_UK_STANDARD','United Kingdom - Standard',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_UK_LARGE','United Kingdom - Large',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_CHINA','China',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_CHINA_DESC','A script-driven map that resembles the shape and terrain of China, completely randomized.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_CHINA_DUEL','China - Duel',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_CHINA_TINY','China - Tiny',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_CHINA_SMALL','China - Small',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_CHINA_STANDARD','China - Standard',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_CHINA_LARGE','China - Large',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_RUSSIA','Russia',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_RUSSIA_DESC','A map of Russia, where the landform is constant, and all the internal terrain is randomized.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_RUSSIA_DUEL','Russia - Duel',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_RUSSIA_TINY','Russia - Tiny',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_RUSSIA_SMALL','Russia - Small',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_RUSSIA_STANDARD','Russia - Standard',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_RUSSIA_LARGE','Russia - Large',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_RUSSIA_HUGE','Russia - Huge',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_TURKEY','Turkey',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_TURKEY_DESC','A map of Turkey, where the landform is constant, and all internal terrain is mountainous and randomized.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_TURKEY_DUEL','Turkey - Duel',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_TURKEY_TINY','Turkey - Tiny',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_TURKEY_SMALL','Turkey - Small',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_TURKEY_STANDARD','Turkey - Standard',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_TURKEY_LARGE','Turkey - Large',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_TURKEY_HUGE','Turkey - Huge',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_FRANCE','France',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_FRANCE_DESC','A map of France, where the landform is constant, and all internal terrain is randomized.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_FRANCE_DUEL','France - Duel',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_FRANCE_TINY','France - Tiny',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_FRANCE_SMALL','France - Small',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_FRANCE_STANDARD','France - Standard',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_FRANCE_LARGE','France - Large',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('en_US','TXT_KEY_CW_MAP_PACK_FRANCE_HUGE','France - Huge',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_AUSTRALIA','Australie',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_AUSTRALIA_DESC','Une carte de l\'Australie, où les terrains sont générés aléatoirement et les points de départ sur la côte.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_AUSTRALIA_DUEL','Australie - Duel',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_AUSTRALIA_SMALL','Australie - Petite',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_AUSTRALIA_STANDARD','Australie - Normale',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_AUSTRALIA_TINY','Australie - Minuscule',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_CANADA','Canada',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_CANADA_DESC','Une carte du Canada, recouverte de toundra et de neige au nord, et contenant des étendues de plaines, de prairies et de forêts générées aléatoirement.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_CANADA_DUEL','Canada - Duel',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_CANADA_LARGE','Canada - Grande',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_CANADA_SMALL','Canada - Petite',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_CANADA_STANDARD','Canada - Normale',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_CANADA_TINY','Canada - Minuscule',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_CHINA','Chine',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_CHINA_DESC','Une carte basée sur le script et ressemblant à celle de la Chine de part ses terrains et la forme de ses terres. Tout y est entièrement aléatoire.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_CHINA_DUEL','Chine - Duel',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_CHINA_LARGE','Chine - Grande',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_CHINA_SMALL','Chine - Petite',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_CHINA_STANDARD','Chine - Normale',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_CHINA_TINY','Chine - Minuscule',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_FRANCE','France',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_FRANCE_DESC','Une carte de la France où la forme des terres est constante, mais où le type de terrain est aléatoire.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_FRANCE_DUEL','France - Duel',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_FRANCE_HUGE','France - Immense',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_FRANCE_LARGE','France - Grande',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_FRANCE_SMALL','France - Petite',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_FRANCE_STANDARD','France - Normale',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_FRANCE_TINY','France - Minuscule',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_ITALY','Italie',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_ITALY_DESC','Une carte de l\'Italie, où la forme terrestre et les Alpes sont constantes, mais où le terrain est aléatoire.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_ITALY_SMALL','Italie - Petite',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_ITALY_STANDARD','Italie - Normale',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_JAPAN','Japon',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_JAPAN_DESC','Carte du Japon, où la forme des terres émergées et des principales chaînes de montagnes sont constantes, mais où le terrain est aléatoire.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_JAPAN_DUEL','Japon - Duel',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_JAPAN_LARGE','Japon - Grande',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_JAPAN_SMALL','Japon - Petite',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_JAPAN_STANDARD','Japon - Normale',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_JAPAN_TINY','Japon - Minuscule',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_RUSSIA','Russie',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_RUSSIA_DESC','Une carte de la Russie, où les formes terrestres sont constantes, mais où le terrain est aléatoire.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_RUSSIA_DUEL','Russie - Duel',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_RUSSIA_HUGE','Russie - Immense',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_RUSSIA_LARGE','Russie - Grande',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_RUSSIA_SMALL','Russie - Petite',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_RUSSIA_STANDARD','Russie - Normale',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_RUSSIA_TINY','Russie - Minuscule',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_SCAN','Scandinavie',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_SCAN_DESC','Une carte de la Scandinavie, générée aléatoirement à l\'exception de certaines caractéristiques clés.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_SCAN_LARGE','Scandinavie - Grande',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_SCAN_SMALL','Scandinavie - Petite',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_SCAN_STANDARD','Scandinavie - Normale',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_TURKEY','Turquie',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_TURKEY_DESC','Une carte de la Turquie où les formes terrestres sont constantes, mais où le terrain est montagneux et aléatoire.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_TURKEY_DUEL','Turquie - Duel',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_TURKEY_HUGE','Turquie - Immense',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_TURKEY_LARGE','Turquie - Grande',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_TURKEY_SMALL','Turquie - Petite',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_TURKEY_STANDARD','Turquie - Normale',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_TURKEY_TINY','Turquie - Minuscule',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_UK','Royaume-Uni',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_UK_DESC','Une carte du Royaume-Uni, incluant l\'Angleterre, l\'Écosse et l\'Irlande du Nord, dont le terrain est aléatoire.',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_UK_DUEL','Royaume-Uni - Duel',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_UK_LARGE','Royaume-Uni - Grande',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_UK_SMALL','Royaume-Uni - Petite',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_UK_STANDARD','Royaume-Uni - Normale',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_CW_MAP_PACK_UK_TINY','Royaume-Uni - Minuscule',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_MAP_FOLDER_DLC_3_DESC','Pack de cartes Nations dispersées',NULL,NULL);
INSERT INTO LocalizedText (Language,Tag,Text,Gender,Plurality) VALUES ('fr_FR','TXT_KEY_MAP_FOLDER_DLC_3_TITLE','Nations dispersées',NULL,NULL);
DROP TABLE IF EXISTS ScannedFiles;
CREATE TABLE ScannedFiles (
  Path text NOT NULL,
  DateTime integer NOT NULL,
  PRIMARY KEY (Path)
);

INSERT INTO ScannedFiles (Path,DateTime) VALUES ('Assets\SQL\Civ5DlcLocalizationDatabaseSchema.sql',130330260200000000);
INSERT INTO ScannedFiles (Path,DateTime) VALUES ('Assets\DLC\Shared\Gameplay\XML\Text\DE_DE\CIV5GameTextInfos_Civilopedia_NaturalWonders.xml',130330260120000000);
INSERT INTO ScannedFiles (Path,DateTime) VALUES ('Assets\DLC\Shared\Gameplay\XML\Text\EN_US\CIV5GameTextInfos_Civilopedia_NaturalWonders.xml',130330260120000000);
INSERT INTO ScannedFiles (Path,DateTime) VALUES ('Assets\DLC\Shared\Gameplay\XML\Text\FR_FR\CIV5GameTextInfos_Civilopedia_NaturalWonders.xml',130330260120000000);
INSERT INTO ScannedFiles (Path,DateTime) VALUES ('Assets\DLC\Shared\Gameplay\XML\Text\DE_DE\CIV5GameTextInfos_Objects_NaturalWonders.xml',130330260120000000);
INSERT INTO ScannedFiles (Path,DateTime) VALUES ('Assets\DLC\Shared\Gameplay\XML\Text\EN_US\CIV5GameTextInfos_Objects_NaturalWonders.xml',130330260120000000);
INSERT INTO ScannedFiles (Path,DateTime) VALUES ('Assets\DLC\Shared\Gameplay\XML\Text\FR_FR\CIV5GameTextInfos_Objects_NaturalWonders.xml',130330260120000000);
INSERT INTO ScannedFiles (Path,DateTime) VALUES ('Assets\DLC\Shared\Gameplay\XML\Text\DE_DE\CIV5GameTextInfos_DLC_SP_Maps.xml',130330260120000000);
INSERT INTO ScannedFiles (Path,DateTime) VALUES ('Assets\DLC\Shared\Gameplay\XML\Text\EN_US\CIV5GameTextInfos_DLC_SP_Maps.xml',130330260120000000);
INSERT INTO ScannedFiles (Path,DateTime) VALUES ('Assets\DLC\Shared\Gameplay\XML\Text\FR_FR\CIV5GameTextInfos_DLC_SP_Maps.xml',130330260120000000);
INSERT INTO ScannedFiles (Path,DateTime) VALUES ('Assets\DLC\Shared\Gameplay\XML\Text\DE_DE\CIV5GameTextInfos_DLC_SP_Maps_2.xml',130330260120000000);
INSERT INTO ScannedFiles (Path,DateTime) VALUES ('Assets\DLC\Shared\Gameplay\XML\Text\EN_US\CIV5GameTextInfos_DLC_SP_Maps_2.xml',130330260120000000);
INSERT INTO ScannedFiles (Path,DateTime) VALUES ('Assets\DLC\Shared\Gameplay\XML\Text\FR_FR\CIV5GameTextInfos_DLC_SP_Maps_2.xml',130330260120000000);
INSERT INTO ScannedFiles (Path,DateTime) VALUES ('Assets\DLC\Shared\Gameplay\XML\Text\DE_DE\CIV5GameTextInfos_DLC_SP_Maps_3.xml',130330260120000000);
INSERT INTO ScannedFiles (Path,DateTime) VALUES ('Assets\DLC\Shared\Gameplay\XML\Text\EN_US\CIV5GameTextInfos_DLC_SP_Maps_3.xml',130330260120000000);
INSERT INTO ScannedFiles (Path,DateTime) VALUES ('Assets\DLC\Shared\Gameplay\XML\Text\FR_FR\CIV5GameTextInfos_DLC_SP_Maps_3.xml',130330260120000000);
DROP TABLE IF EXISTS Language_DE_DE;
CREATE TABLE Language_DE_DE (
  Tag text,
  Text text,
  Gender text,
  Plurality text
);
CREATE VIEW Language_DE_DE AS SELECT Tag, Text, Gender, Plurality from LocalizedText where Language = 'de_DE'

CREATE TRIGGER Language_DE_DE_insert INSTEAD OF INSERT ON Language_DE_DE BEGIN insert into LocalizedText(Language, Tag, Text, Gender, Plurality) VALUES('de_DE', NEW.Tag, NEW.Text, NEW.Gender, NEW.Plurality); END;

CREATE TRIGGER Language_DE_DE_update INSTEAD OF UPDATE ON Language_DE_DE BEGIN UPDATE LocalizedText SET Text = NEW.Text , Gender = NEW.Gender, Plurality = NEW.Plurality WHERE Language = 'de_DE' and Tag = NEW.Tag; END;

CREATE TRIGGER Language_DE_DE_delete INSTEAD OF DELETE ON Language_DE_DE BEGIN DELETE from LocalizedText where Language = 'de_DE' and Tag = OLD.Tag; END;

CREATE VIEW Language_FR_FR AS SELECT Tag, Text, Gender, Plurality from LocalizedText where Language = 'fr_FR'

CREATE TRIGGER Language_FR_FR_insert INSTEAD OF INSERT ON Language_FR_FR BEGIN insert into LocalizedText(Language, Tag, Text, Gender, Plurality) VALUES('fr_FR', NEW.Tag, NEW.Text, NEW.Gender, NEW.Plurality); END;

CREATE TRIGGER Language_FR_FR_update INSTEAD OF UPDATE ON Language_FR_FR BEGIN UPDATE LocalizedText SET Text = NEW.Text , Gender = NEW.Gender, Plurality = NEW.Plurality WHERE Language = 'fr_FR' and Tag = NEW.Tag; END;

CREATE TRIGGER Language_FR_FR_delete INSTEAD OF DELETE ON Language_FR_FR BEGIN DELETE from LocalizedText where Language = 'fr_FR' and Tag = OLD.Tag; END;

CREATE VIEW Language_en_US AS SELECT Tag, Text, Gender, Plurality from LocalizedText where Language = 'en_US'

CREATE TRIGGER Language_en_US_insert INSTEAD OF INSERT ON Language_en_US BEGIN insert into LocalizedText(Language, Tag, Text, Gender, Plurality) VALUES('en_US', NEW.Tag, NEW.Text, NEW.Gender, NEW.Plurality); END;

CREATE TRIGGER Language_en_US_update INSTEAD OF UPDATE ON Language_en_US BEGIN UPDATE LocalizedText SET Text = NEW.Text , Gender = NEW.Gender, Plurality = NEW.Plurality WHERE Language = 'en_US' and Tag = NEW.Tag; END;

CREATE TRIGGER Language_en_US_delete INSTEAD OF DELETE ON Language_en_US BEGIN DELETE from LocalizedText where Language = 'en_US' and Tag = OLD.Tag; END;